// <auto-generated />
using BlogBlazor.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogBlazor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200912165418_IntialMigration")]
    partial class IntialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("BlogBlazor.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Aji Mustofa",
                            Body = "Post by aji mustofa",
                            Summary = "Post pertama",
                            Title = "Post Aji"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Gina",
                            Body = "Post by gina",
                            Summary = "Post kedua",
                            Title = "Post Gina"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Pepeg",
                            Body = "Post by pepega",
                            Summary = "Post ketiga",
                            Title = "Post KEKW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
